#!/bin/bash
# This is an example catalystrc. As such, it doesn't actually *do* anything.

# Uncomment the following to increase the number of threads used to compile.
export MAKEOPTS="-j6"
export CCACHE_DIR="/var/ccache" 
export CCACHE_SIZE="2G" 
export PYTHON_TARGETS="python2_7"
export DONT_MOUNT_BOOT="1"
export TERM='xterm-color'
